### Assign Task

PATCH http://localhost:5000/api/tasks/f125fc6c-78ae-41cd-b943-4a9ef8031b3e/assign
Authorization: Bearer token
Content-Type: application/json


{
    "assignedToId":"12f28d1f-0f71-4076-93a4-822e6a04c116"
}