### Logout

POST http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjZkN2IzOS1mMThhLTQ5OWMtYjJlOS03NDE0ZjMzODcxM2EiLCJpYXQiOjE3ODU1Nzc4MTgsImV4cCI6MTc4NjE4MjYxOH0.BRIxowZVg4oY5498qLPfUp_3mXl_LNrxBJirSpnLAgY"
}