POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"harsha@gmail.com",
    "password":"xyz"
}

### Login User 2

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "karthi@gmail.com",
    "password": "xyz"
}

### Login User 3

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "Aruna@gmail.com",
    "password": "xyz"
}


### Login user 4

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "laasya@gmail.com",
    "password": "xyz"
}
