### Create Task

POST http://localhost:5000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjZkN2IzOS1mMThhLTQ5OWMtYjJlOS03NDE0ZjMzODcxM2EiLCJpYXQiOjE3ODQwNTI1OTAsImV4cCI6MTc4NDA1MzQ5MH0.WWtTRs3MR0neQRDs1xdOi6S7B6ViNybBoRbqfiE9Peo
Content-Type: application/json


{
    "title":"Implement JWT Authentication",

    "description":"Create login and refresh token APIs",

    "projectId":"ef3a8905-dcb6-470a-a349-ae7ee99db659",

    "priority":"HIGH",

    "dueDate":"2026-08-01T00:00:00Z"
}