### Create Project

POST http://localhost:5000/api/projects
Authorization: Bearer token
Content-Type: application/json

{
    "name":"Authentication Module",

    "description":"Implement complete authentication flow",

    "workspaceId":"74e81c0d-e87e-4fad-a3fe-2adc89ac6023",

    "status":"PLANNING"
}
### Create Project


POST http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjZkN2IzOS1mMThhLTQ5OWMtYjJlOS03NDE0ZjMzODcxM2EiLCJpYXQiOjE3ODQwNTMzMzYsImV4cCI6MTc4NDA1NDIzNn0.gvVZOnAkyHr_ei7KtEUNiZsC9jOIHjjySZ0l3X7CHm8
Content-Type: application/json


{
    "name":"Testing Permission Refactor",

    "description":"Checking helper integration",

    "workspaceId":"74e81c0d-e87e-4fad-a3fe-2adc89ac6023"
}