### Update Task

PATCH http://localhost:5000/api/tasks/d0f185a4-700d-40ee-b722-ba133f3e1ebb
Authorization: Bearer token
Content-Type: application/json


{
    "description": "Updated implementation details"
}