### Update Workspace

PATCH http://localhost:5000/api/workspaces/474830c4-628f-419f-ac66-da711e8fe3f8
Authorization: Bearer token
Content-Type: application/json


{
    "name":"Backend Engineering Team"
}